apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/juandiegocv27/cluster-gitops
    targetRevision: dev    
    path: apps/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
