apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/juandiegocv27/cluster-gitops
    targetRevision: main
    path: apps/catalog/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: catalog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
